plugins {
    id 'com.android.application'
}

android {
    namespace 'com.danyusha.beautyrun'
    compileSdk 35

    defaultConfig {
        applicationId 'com.danyusha.beautyrun'
        minSdk 23
        targetSdk 28
        versionCode 4
        versionName '0.4.0'
        testInstrumentationRunner 'com.danyusha.beautyrun.SmokeInstrumentation'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
